url: "http://andreabochicchio.github.io/enquete-vie-sociale-des-donnees_Data-Breach/"

title: "Enquête La vie sociale des données - base de données Data Breach Chronology"
description: "Par Andrea Bochicchio, Nancy-Wangue Moussissa et Ayesha VeerasuntharamCette enqûete abordera une base de données qui recueille les fuites de données aux États-Unis, en l'observant et en pourvoyant une analyse structurée de l'utilité d'une telle base de données, de ses enjeux et de ses conséquences."
color_theme: dark

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
