url: "http://andreabochicchio.github.io/enquete-vie-sociale-des-donnees_Data-Breach/"

title: "Enquête La vie sociale des données - Base de données Data Breach Chronology"
description: "Par Andrea Bochicchio, Nancy-Wangue Moussissa et Ayesha Veerasuntharam"
color_theme: dark

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
