url: "http://andreabochicchio.github.io/enquete-vie-sociale-des-donnees_Data-Breach/"

color_theme: dark                     # color theme auto, dark or light

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
