baseurl: "http://andreabochicchio.github.io/enquete-vie-sociale-des-donnees_Data-Breach/"
url: "http://andreabochicchio.github.io/enquete-vie-sociale-des-donnees_Data-Breach/"
plugins: [jekyll-remote-theme]

title: My Jekyll Blog                 # Name of website
avatar: assets/img/avatar.png         # Path of avatar image, to be displayed in the theme's header
description: My blog posts            # Short description, primarily used by search engines
favicon: assets/favicon.ico           # Icon displayed in the tab
color_theme: dark                     # color theme auto, dark or light

theme: minimal
remote_theme: pages-themes/slate@v0.2.0
